backend:
  name: git-gateway

media_folder: "static/assets"
public_folder: "assets"

# Verkefni
collections:
  - name: "verkefni"
    label: "Verkefni"
    folder: "static/content/verkefni"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Lýsing", name: "lysing", widget: "text" }
      - label: "Hvað var gert?"
        name: "hvad-var-gert"
        widget: "select"
        multiple: true
        options:
          [
            "Vefun",
            "Grafísk Hönnun",
            "Hugmyndavinna",
            "Mörkun",
            "Framleiðsla",
            "Hönnun",
            "Textavinna",
            "Samfélagsmiðlun",
            "Stefnumótun",
            "Letur",
            "Tökur",
          ]
      - { label: "Kúnni", name: "kunni", widget: "string" }
      - {
          label: "Forsíðu mynd",
          name: "forsidu-mynd",
          widget: "image",
          required: false,
        }
      - {
          label: "Forsíðu myndband",
          name: "forsidu-myndband",
          widget: "file",
          required: false,
        }
      - {
          label: "Forsíðu gif",
          name: "forsidu-gif",
          widget: "file",
          required: false,
        }
      - {
          label: "Efsta Mynd",
          name: "efsta-mynd",
          widget: "image",
          hint: "Þessi mynd birtist efst í stöku verki",
        }
      - label: "Myndir & Myndbönd"
        name: "myndir-og-myndbond"
        widget: "list"
        fields:
          - { label: "Mynd", name: "mynd", widget: "image", required: false }
          - {
              label: "Myndband",
              name: "myndband",
              widget: "file",
              required: false,
            }
