backend:
  name: git-gateway

media_folder: "static/myndir"
public_folder: "myndir"

collections:
  # Verkefni
  - name: "verkefni"
    label: "Verkefni"
    folder: "static/content/verkefni"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Dagsetning",
          name: "dagsetning",
          widget: "datetime",
          format: "MM-YYYY",
          hint: "Verkum er raðað eftir dagsetningu á síðunni, þannig ef þú vilt færa verk framar - breyttu þá dagsetninunni.",
        }
      - { label: "Lýsing", name: "lysing", widget: "text" }
      - label: "Hvað var gert?"
        name: "hvad-var-gert"
        widget: "select"
        multiple: true
        options:
          [
            "Vefun",
            "Grafísk Hönnun",
            "Hugmyndavinna",
            "Mörkun",
            "Framleiðsla",
            "Hönnun",
            "Textavinna",
            "Samfélagsmiðlun",
            "Stefnumótun",
            "Letur",
            "Tökur",
            "Hreyfigrafík",
          ]
      - { label: "Kúnni", name: "kunni", widget: "string" }
      - {
          label: "Á forsíðu",
          name: "aforsidu",
          widget: "boolean",
          required: false,
        }
      - label: "Forsíðu mynd",
        name: "forsidumynd",
        widget: "object",
        required: false,
        hint: "Má vera mynd, gif eða video. Settu thumbnail ef þetta er vidjó!",
        fields:
          - { label: "Skrá", name: "skra", widget: "file", required: false }
          - {
              label: "Thumbnail",
              name: "thumb",
              widget: "image",
              default: "content/myndir/third.jpg",
              required: false,
              hint: "Settu thumbnail ef þetta er myndband.",
            }
      - {
          label: "Efsta Mynd",
          name: "efstamynd",
          widget: "image",
          hint: "Þessi mynd birtist efst í stöku verki, verður að vera mynd!",
        }
      - label: "Myndir & Myndbönd"
        name: "hlutir"
        widget: "list"
        fields:
          - label: "Mynd/Myndband"
            name: "hlutur"
            widget: "object"
            required: false
            fields:
              - { label: "Skrá", name: "skra", widget: "file", required: false }
              - {
                  label: "Thumbnail",
                  name: "thumb",
                  widget: "image",
                  default: "content/myndir/third.jpg",
                  required: false,
                  hint: "Settu thumbnail ef þetta er myndband.",
                }
  # Stofan
  - name: "stofan"
    label: "Stofan"
    folder: static/content/stofan
    editor:
      preview: false
    create: true
    fields:
      - { name: "title", label: "Titill", widget: "string" }
      - { name: "body", label: "Um Tvist", widget: "markdown" }
      - { name: "efstavideo", label: "Efsta myndband", widget: "file" }
  # Kúnnar
  - name: "kunnar"
    label: "Kúnnar"
    folder: static/content/kunnar
    editor:
      preview: false
    create: true
    fields:
      - { name: "title", label: "Nafn", widget: "string" }
      - { name: "mynd", label: "Mynd", widget: "image" }
  # Starfsmenn
  - name: "starfsmenn"
    label: "Starfsmenn"
    folder: static/content/starfsmenn
    editor:
      preview: false
    create: true
    fields:
      - { name: "title", label: "Nafn", widget: "string" }
      - { name: "mynd", label: "Mynd", widget: "image" }
      - label: "Starf"
        name: "starf"
        widget: "select"
        multiple: true
        options:
          [
            "Stofnandi / Creative director",
            "Stofnandi / Hönnunarstjóri",
            "Gæðastjóri / Art director",
            "Grafískur Hönnuður",
            "Art director",
            "Hugmynda- og textasmiður",
            "Verkefnastjóri",
          ]
      - { name: "netfang", label: "Netfang", widget: "string" }
